### ISSUE TITLE
[+/- voice] assimilation

### ISSUE THREAD

**Issue by koghuzhan** [apertium/apertium-uig-tur#4]
For foreign words ending with a voiced consonant like gherb, kitab that take voiceless suffixes something similar to "force front/back harmony" characters (used for vowel harmony) can/should be used.

**Comment by MemduhG** [comment]
Do we still have this problem? Seems like a twol variable in uig could fix this but you've probably already thought of that :D

**Comment by ftyers** [comment]
How about marking them with `%{☫%}` ? @jonorthwash do you remember what that was for ?

**Comment by koguzhan** [comment]
Yes, I recently added {q} to take care of that, it seems to be working. %{☫%} is mostly for loanwords too but it blocks the vowel reduction process.

**Comment by koghuzhan** [comment]
Yes, I recently added {q} to take care of that, it seems to be working. %{☫%} is mostly for loanwords too but it blocks the vowel reduction process.
