### ISSUE TITLE
Evaluation Text

### ISSUE THREAD

**Issue by MemduhG** [apertium/apertium-uig-tur#6]
* Pick a text of 200-500 tokens
* Either postedit the translation to be legitimate turkish or use a pre-existing turkish translation*
* Run a WER script** apertium-uig-tur output with the corrected output or the turkish translation
* Put the results in `apertium-uig-tur/texts`

*I think we can use something from Mahinur Uygur's bilingual fable book, that would also spare us the process of post-editing.
**We have a script for calculating this, I will show you how to run it.

This should be the last issue for this milestone :grinning:

**Comment by koghuzhan** [comment]
Done.
